services:
  db:
    image: postgres:17-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: sleep infinity

volumes:
  postgres_data: