services:
  db:
    image: pgvector/pgvector:pg17
    # Automatically restarts the container after a system reboot or database crash
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_vector_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
    volumes:
      # Mounts code to /workspace.
      # The :cached flag optimizes the filesystem on macOS; it's natively ignored on Ubuntu, but good practice.
      - .:/workspace:cached
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    # Doesn't start the app immediately. Keeps the container alive in the background
    # so it is possible to freely connect via the terminal and manually run code.
    command: sleep infinity

volumes:
  postgres_vector_data:
