name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.TEST_SECRET_KEY }}
      ALGORITHM: ${{ secrets.TEST_ALGORITHM }}
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      GOOGLE_API_KEY: mock-google-api-key-for-testing
    services:
      postgres:
        image: pgvector/pgvector:pg17
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6 # Checkout the repository to the GitHub Actions runner

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true # Enable caching for uv dependencies
          cache-dependency-glob: uv.lock # Cache dependencies based on the uv.lock file (not pyproject.toml and others, which may change more frequently)

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: uv sync --dev --frozen # Flag --frozen ensures that the exact versions specified in uv.lock are installed, preventing updating it based on pyproject.toml changes

      - name: Check formatting with Ruff
        run: uv run ruff format --check . # Check code formatting with Ruff, using --check to only report issues without modifying files

      - name: Lint code with Ruff
        run: uv run ruff check --output-format=github . # Use --output-format=github to format linting results in a way that GitHub can parse and display inline in the pull request

      - name: Run tests
        run: uv run pytest
