name: Lint Commit Messages

on:
  pull_request:
    branches:
      - main

jobs:
  commitlint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 1 by default, this is required to get the full commit history for linting

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install conventional-changelog-conventionalcommits

      - name: Check commit messages
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: 'commitlint.config.mjs'
